Improved the useEffect usage
EclipseFdn/react-eclipsefdn-members pull request #107
Opened 2021-06-14 14:14 UTC by linkfang

For [issue93](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/93)

- Added all dependencies suggested by ESLint.

- Instead of using useEffect in CompanyInformationContacts component, now it's using onChange (of some input components) to handle the logic

2021-06-14 14:48 UTC, autumnfound requested changes
General comment: We should set up a prettifier config to share. We usually extend line length to something like 120 or 140 as the typical 80 makes stuff look really compressed for no real reason

2021-06-14 14:48 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +      if (
We typically keep these on one line, not breaking them into separate lines. If they pass the line length max, we just move the last clause to next line with an indent. Additionally, we put logic outside of the parentheses usually. I've never actually seen it inside :thinking:

2021-06-14 14:48 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
Binding use effect to formik seems like an odd choice. Wouldn't this cause it to fire waaay more often than it should?

2021-06-14 14:48 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformationContacts.js
>              value={formik.values.representative[`${type}`][`${el.name}`]}
why use interpolation here? Wouldn't it just allow you to have the variables in there as its escaped from JSX?

2021-06-14 14:48 UTC, autumnfound commented on src/main/www/src/components/Pages/Main.js
> +        {window.location.hash === '/' ||
why keep this separated when we can bake it into the sign-in route?

2021-06-14 14:48 UTC, autumnfound commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +  }, [
this probably doesn't need to be broken up like this

2021-06-14 15:39 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +      if (
> General comment: We should set up a prettifier config to share. We usually extend line length to something like 120 or 140 as the typical 80 makes stuff look really compressed for no real reason

OK, I set it as 120 and will apply this to the files you mentioned. (Like, for conditions in if statement and dependency array for useEffect, etc.)

And I think I'd better apply it to all files in another PR just to make sure this format change won't overwhelm the useEffect related changes.

2021-06-14 15:50 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +      if (
> Additionally, we put logic outside of the parentheses usually. I've never actually seen it inside 🤔

Sorry, I don't quite understand this feedback. Do you mean put the function definition outside of the parentheses of useEffect?

If this is the case, I had the same thoughts but then found that React did not recommend we do it this way. Refer here (the first gif): https://github.com/facebook/react/issues/14920

2021-06-14 16:09 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
> Binding use effect to formik seems like an odd choice. Wouldn't this cause it to fire waaay more often than it should?

Yeah, I do agree with you. And the reason I do it this way is because that's what ESLint recommends us to do. If I remove formik from the array, ESLint will complain that there is a missing dependency and this warning will stop the commit/PR from passing the checks. ESLint would like to have everything we use in useEffect to be in the dependency array, and I do use formik in it.

And useEffect won't fire way more times than it should, will likely fire 1-2 more times, but won't do extra API call, because of the if statement we have in it. 

Like the first time the user enters the page with "continue with existing" option, useEffect will be triggered, then fetch call (detectModeAndFetch) will be triggered, then the value in formik will be updated. This update/change will trigger useEffect again because formik is one of the dependencies, but then in the if statement, it will find out the organization.id already exist, so there will not be another fetch call and so useEffect won't be triggered again after this.

2021-06-14 16:12 UTC, linkfang commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +  }, [
> this probably doesn't need to be broken up like this

Yep, after I set the printWidth to 120, Prettier makes them in one line now.

2021-06-14 17:43 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformationContacts.js
>              value={formik.values.representative[`${type}`][`${el.name}`]}
Oh, yes, it works. 
I was trying to solve some strange issues when use array.map with useFormik(), my brain must be a jam after figured it out😂. Will change them to just variables.

2021-06-14 18:02 UTC, linkfang commented on src/main/www/src/components/Pages/Main.js
> +        {window.location.hash === '/' ||
> why keep this separated when we can bake it into the sign-in route?

I did put it inside sign-in route, but then I realised this sign in introduction should be above the steppers (6 steps). So, if I kept it in sign-in route, it will be beneath the steppers. And so, I moved it outside of the route and above the steppers (renderSteppers()) to match the design.
![image](https://user-images.githubusercontent.com/43075439/121937755-0368ac00-cd19-11eb-87ea-2f15a357045f.png)

2021-06-14 18:14 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
Just found a bug which will fire useEffect on Membership Level page/step infinitely. But it won't be an issue after [PR98](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/98) being merged in, as I changed some fetch logic based on the new formfields. Will test it out after that PR is in.

2021-06-14 18:43 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
Whats the message being returned by ESLint? From what I understand, the variables you pass in that array get stuck into a listener and when any of them change it fires this event. Formik holds way more than form state, and is more or less just a framework no? Its statically present as a thing once created at the start of the app, and then is just a blob.

My hunch is that the regex that powers that rule sees us call formik and says ah yes, we should watch for that. This is a case where we want to disable that rule on this line, or find a way to add formik as an exception.

2021-06-14 18:45 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
The TLDR of what I'm getting at is that ESLint isn't always right, but its usually pretty good. We can work around it, or temporarily disable the rule while we look into why its firing off here. An alternative as well, is that we make it an info level issue that doesn't block builds but says that it _could_ be a problem maybe.

2021-06-14 18:46 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +      if (
Doh. My coffee hadn't kicked in. 

FTFY:
We put logic **comments** outside of parentheses.

2021-06-14 19:21 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
> Whats the message being returned by ESLint?

src/components/Pages/CompanyInformation/CompanyInformation.js
Line 138:6:  React Hook useEffect has a missing dependency: 'formik'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
![image](https://user-images.githubusercontent.com/43075439/121946260-be497780-cd22-11eb-80d1-5218efe8d485.png)

Yeah, it is more than a form state. But I think the form state/value is the only thing that will be updated/changed, all the other stuff (helper text, setter method, handle onChange, etc.) will be static once the formik instance is created.
But yeah, I am good to temporarily disable the rule for those ones that suggest adding formik in the array and make it an info level issue before we solve it.

2021-06-14 19:27 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +      if (
> Doh. My coffee hadn't kicked in.
> 
> FTFY:
> We put logic **comments** outside of parentheses.

Haha, OK, will move them out.

2021-06-14 19:44 UTC, autumnfound commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
Looking into it, it is heavily discouraged to disable it fully, because when it pops up its either you are missing something or doing something wrong. I think that to get this in considering the depth of changes, I would create a technical debt issue to track reenabling it so we can get this in rather than split hairs!

https://stackoverflow.com/a/58959607

2021-06-14 20:12 UTC, linkfang commented on src/main/www/src/components/Pages/CompanyInformation/CompanyInformation.js
> +  }, [isStartNewForm, formik, currentFormId, furthestPage.index]);
Yep, same based on my research. Most people/articles suggest to include the dependencies suggested by ESLint and solve the issue it brings (like using useCallback), or to think about the code if we really need to do that operation in useEffect.

So I deleted 2 useEffect in CompanyInformationContacts component and use onChange to do the work instead.
in other cases/components, we do need to do the API call and set the values after we get them, so we have to use formik.setFieldValue. That's why I added all the dependencies and did some changes to make sure it won't run into an infinite loop.

2021-06-21 14:22 UTC, autumnfound commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +    if (!isStartNewForm && !hasWGData && fullWorkingGroupList.length > 0) {
If you moved the const defined in the useEffect out of the block and into the general functional component area, wouldn't that remove the dependency on wg list and set value from the useEffect? I'm still learning and trying to understand

2021-06-21 14:53 UTC, linkfang commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +    if (!isStartNewForm && !hasWGData && fullWorkingGroupList.length > 0) {
Yep, it will. 

But then it will ask us to add the function into the dependency array.
And refer to React's doc, they recommend us to declare the function inside useEffect if that's the only place we use it.
https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

2021-06-21 15:03 UTC, autumnfound commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +    if (!isStartNewForm && !hasWGData && fullWorkingGroupList.length > 0) {
Reading more of that page, it looks like some of this should be memoized for best performance, but this is definitely better!

2021-06-21 15:22 UTC, linkfang commented on src/main/www/src/components/Pages/WorkingGroups/WorkingGroupsWrapper.js
> +    if (!isStartNewForm && !hasWGData && fullWorkingGroupList.length > 0) {
Yeah, right.
In our case, as the function is inside the useEffect, so we don't need to memoize it to prevent extra/unnecessary triggers. 
And except the fullWorkingGroupList, which will change once after we get the data, all other dependencies won't change after user starts the form. So, no need to memoize them as well.

2021-06-22 12:40 UTC, merged