Migrated Review component to ts version
EclipseFdn/react-eclipsefdn-members pull request #113
Opened 2021-06-16 21:17 UTC by linkfang

2021-06-17 12:58 UTC, autumnfound commented on src/main/www/src/components/Pages/Main.js
> +import Review from './Review/Review.tsx';
Do you need to define this? You only have one file so it should be able to detect it shouldn't it?

2021-06-17 13:21 UTC, linkfang commented on src/main/www/src/components/Pages/Main.js
> +import Review from './Review/Review.tsx';
For yarn start, /Review works perfectly, but not for the docker version. If I remove the .tsx, it will try to find /Review.js and then give me an error like so:
![image](https://user-images.githubusercontent.com/43075439/122404342-2380b100-cf4d-11eb-810e-e3c563900848.png)

2021-06-17 14:24 UTC, linkfang commented on src/main/www/src/components/Pages/Main.js
> +import Review from './Review/Review.tsx';
OK, after restart the docker instance, everything works fine!

2021-06-17 18:20 UTC, chrisguindon requested changes

2021-06-17 18:20 UTC, chrisguindon commented on src/main/www/src/components/Pages/Review/Review.tsx
> +interface Props {
I would name this ReviewProps

2021-06-17 18:20 UTC, chrisguindon commented on src/main/www/src/Constants/Interface.tsx
> +export interface workingGroups {
Since an interfance is like a class, I think they should always start with a capital letter.

2021-06-17 18:20 UTC, chrisguindon commented on src/main/www/src/Constants/Interface.tsx
> +export interface FormValue {
It will get messy if we add all our shared interfaces in 1 file. I think we should use this structure: https://stackoverflow.com/questions/36633033/how-to-organize-typescript-interfaces/55941782#55941782

2021-06-18 13:28 UTC, linkfang commented on src/main/www/src/Constants/Interface.tsx
> +export interface workingGroups {
Yeah, I thought I did also use capital letter for workinggroup, but seems not😂

2021-06-18 13:56 UTC, autumnfound commented
I don't see the files from the interface folder, I think they were missed

2021-06-18 13:59 UTC, linkfang commented
> I don't see the files from the interface folder, I think they were missed

Oh, yes, I only did "commit -am", and forgot to do "add ." first, lol. Now it's good

2021-06-22 12:35 UTC, merged