Add unit tests for various parts of API
EclipseFdn/react-eclipsefdn-members pull request #126
Opened 2021-06-18 20:36 UTC by autumnfound

2021-06-30 17:15 UTC, autumnfound commented
This is failing to build as there is an upstream change to be merged from eclipsefdn-api-commons

2021-07-01 08:21 UTC, mbarbero requested changes

2021-07-01 08:21 UTC, mbarbero commented on src/main/java/org/eclipsefoundation/react/bootstrap/DataLoaderConfig.java
> +    private List<String> userIds = Arrays.asList("malowe", "cguindon", "epoirier", "zhoufang");
why is there hard coded username in the main src? This should be test data at best.

2021-07-06 15:44 UTC, mbarbero approved these changes

2021-07-07 19:31 UTC, merged