Zhoufang/master/issue117 landing page
EclipseFdn/react-eclipsefdn-members pull request #144
Opened 2021-06-25 22:13 UTC by linkfang

For [issue117](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/117) Landing page part

2021-07-13 14:37 UTC, autumnfound commented on src/main/www/src/components/Portal/Dashboard/Dashboard.tsx
> +      <h2>Overview</h2>
This should be using the typography component

2021-07-13 14:37 UTC, autumnfound commented on src/main/www/src/components/Portal/Dashboard/DashboardFAQs.tsx
> +      <h2>FAQs</h2>
Typography component here

2021-07-13 14:37 UTC, autumnfound commented on src/main/www/src/components/Portal/Portal.tsx
> +          <div className={classes.avatarCtn}>
please see the Avatar component in MUI

2021-07-13 14:37 UTC, autumnfound commented on src/main/www/src/components/Portal/Portal.tsx
> +            <h1>Home</h1>
Se typography component

2021-07-13 14:37 UTC, autumnfound commented on src/main/www/src/components/Portal/NavBar/LeftNavBar.tsx
> +  const navOptions = NAV_OPTIONS_DATA.map((item) => (
Not sure how we want to handle this, but we can inline this pretty easily and it would be decently clean. Might want to include Chris on this

2021-07-13 19:10 UTC, linkfang commented
All the placeholder components are now using "div" and element styles to show a basic layout of the app. They will be replaced with Material-UI components when being implemented.

2021-07-23 14:39 UTC, autumnfound requested changes

2021-07-23 14:39 UTC, autumnfound commented on src/main/www/package.json
> +    "@types/react-router-dom": "^5.1.7",
This is not a dev dependency and should not be in this section

2021-07-23 14:39 UTC, autumnfound commented on src/main/www/src/components/Portal/CommittersAndContributors/CommitersAndContributors.tsx
> +    <div
We should change the root of these panels to be a component to make it easier to maintain

2021-07-23 14:39 UTC, autumnfound commented on src/main/www/src/components/Portal/NavBar/AppTopBar.tsx
> +          {userInfo?.full_name ? userInfo.full_name : 'John Doe'}
Should not use John Doe as placeholder (gendered, and better to use non-gendered placeholders)

2021-07-23 14:39 UTC, autumnfound commented on src/main/www/src/components/Portal/Portal.tsx
> +// import Home from './Home/Home';
Why comment out this code? We can have those routes in and it wouldn't harm the overall product. Its known that this is still early days, and that there will be placeholders while we get content and make components

2021-07-23 18:49 UTC, linkfang commented on src/main/www/package.json
> +    "@types/react-router-dom": "^5.1.7",
This is for react-router-dom to support TypeScript and before I installed it, I had received error message as below which suggested me install it as a dev dependency. 
![image](https://user-images.githubusercontent.com/43075439/126827655-cc6290fb-5776-45ee-9df7-768f69eb5f32.png)

I don't think the type is still useful after React compiles the code into build, because everything will be standard JavaScript after it right?

2021-07-23 19:10 UTC, linkfang commented on src/main/www/src/components/Portal/Portal.tsx
> +// import Home from './Home/Home';
This is something Chris would like to do for now, as he said the Home page seemed to be a duplicated one of Dashboard. I think we can add it back or delete it after we confirmed with Marketing team?

2021-07-23 19:35 UTC, linkfang commented on src/main/www/src/components/Portal/CommittersAndContributors/CommitersAndContributors.tsx
> +    <div
Or I think I can add a padding top and bottom to the parent component of those panels, so that we don't need to set styles for them and no need to add a new component (wrapper). As for now, the only common thing of them is the margin top and bottom. 

If later on we will have more common stuff for them, then we can add one at that time. If not, we can keep things simple. What do you think?

2021-07-23 19:36 UTC, linkfang commented on src/main/www/src/components/Portal/NavBar/AppTopBar.tsx
> +          {userInfo?.full_name ? userInfo.full_name : 'John Doe'}
Sounds good!
I will make the changes in [PR206](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/206), which is specific for the user tool bar

2021-07-26 17:41 UTC, autumnfound commented on src/main/www/src/components/Portal/CommittersAndContributors/CommitersAndContributors.tsx
> +    <div
If this means there is only one place where those CSS classes are defined, I'm happy with that!

2021-07-26 17:43 UTC, autumnfound commented on src/main/www/package.json
> +    "@types/react-router-dom": "^5.1.7",
Looking into this, the answer online seems to be *flails in place*. If we run this through express rather than as compiled JS, it looks like that should be a regular dependency otherwise it doesn't really matter?

2021-07-29 21:52 UTC, linkfang commented on src/main/www/src/components/Portal/CommittersAndContributors/CommitersAndContributors.tsx
> +    <div
Solved with this [commit](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/144/commits/4f0696fe0d368109b258e6ef9b70c168a060faff)

2021-07-30 13:12 UTC, autumnfound approved these changes

2021-07-30 13:12 UTC, merged