Added organization intro section
EclipseFdn/react-eclipsefdn-members pull request #205
Opened 2021-07-21 21:41 UTC by linkfang

For [issue146](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/146)

2021-07-23 14:07 UTC, autumnfound requested changes

2021-07-23 14:07 UTC, autumnfound commented on src/main/www/src/components/Portal/NavBar/LeftNavBar.tsx
> +  if (path.includes('#')) {
We shouldn't look for # to be indicative of routing type. If we want to anchor somewhere on the page, we would use an anchor for that. We should consider splitting this into 2 Types that are interchangable, one being LinkedNavOption and one being NavOption. @chrisguindon wdyt?

2021-07-23 14:07 UTC, autumnfound commented on src/main/www/src/components/Portal/NavBar/AppTopBar.tsx
> +          {userInfo?.full_name ? userInfo.full_name : 'John Doe'}
For no user name, we should use Anonymous. It is non-gendered and more generic.

2021-07-23 14:07 UTC, autumnfound commented on src/main/www/src/components/Portal/Dashboard/DashboardOverview.tsx
> +    <div
We should consider making a SectionBase component that accepts children and prints them within a tag. We've been repeating ourselves a lot, and if we ever want to change how the wrap looks for these panels, it will be a lot of copy paste that is prone to errors.

2021-07-23 14:07 UTC, autumnfound commented on src/main/www/package.json
> +    "@types/react-router-dom": "^5.1.7",
This looks like it might conflict with the real version of 5.2.0 that we have defined above. This should also be a standard dep, not a dev dependency. We ship content that uses this so it is not strictly dev

2021-07-23 14:18 UTC, linkfang commented on src/main/www/src/components/Portal/Dashboard/DashboardOverview.tsx
> +    <div
Ah, no, these are just placeholders.
For this PR, all changes happened in this [commit](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/205/commits/c7fec78f8676d33094c60d935eed4d8e9acb3af2)

All other changes belong to this [one](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/144), I have to include this PR as it is the base one, need to add things with it.

2021-07-30 18:51 UTC, linkfang commented on src/main/www/src/components/Portal/NavBar/AppTopBar.tsx
> +          {userInfo?.full_name ? userInfo.full_name : 'John Doe'}
Done in this [PR](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/206)

2021-07-30 18:52 UTC, linkfang commented on src/main/www/src/components/Portal/Dashboard/DashboardOverview.tsx
> +    <div
Done and merged in landing page PR

2021-07-30 19:17 UTC, linkfang commented
Moved to [PR229](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/229)

2021-07-30 19:17 UTC, closed without merging