Change some autocomplete fields to dropdown menus
EclipseFdn/react-eclipsefdn-members pull request #225
Opened 2021-07-27 19:21 UTC by linkfang

Fixes [issue216](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/216)

2021-07-28 15:22 UTC, autumnfound commented
Code looks good but I can't confirm functionality currently as preview is broken (not from this PR)

2021-07-28 15:26 UTC, linkfang commented
> Code looks good but I can't confirm functionality currently as preview is broken (not from this PR)

Ah, right. I will fix it and push it in the PR. 

For now, after you click the "React Only", you can then click the sign in stepper, then you should be able to see continue with existing button and start new button, and then choose continue with existing.

Or you could wait for a moment, the fix should not take long.

2021-07-28 16:55 UTC, autumnfound requested changes
Checked, if autocomplete is being left in, it needs to properly validate the answer. Reverting to last is not an acceptable bit of logic in this case. It should keep the bad value but inform the user it isn't valid if they try and go to the next step. For optional fields, empty would still be an acceptable response, but with a value, it needs to be valid.

2021-07-30 12:53 UTC, autumnfound approved these changes

2021-07-30 12:54 UTC, merged