Added 3 terms for issue237
EclipseFdn/react-eclipsefdn-members pull request #238
Opened 2021-08-11 20:15 UTC by linkfang

Fixes [issue237](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/237)

2021-08-12 17:21 UTC, linkfang commented
For file Review.tsx, changes between line 31 to line 224 are just format changes. 
The actual changes for the issue are those in other lines.

2021-08-13 17:03 UTC, autumnfound requested changes

2021-08-13 17:03 UTC, autumnfound commented on src/main/www/src/components/Application/Review/Review.tsx
> +    setIsTermChecked(newIsTermChecked);
We don't need the variable declaration here

2021-08-13 17:03 UTC, autumnfound commented on src/main/www/src/components/Application/Review/Review.tsx
> +          <Checkbox name="term" color="primary" required checked={isTermChecked} onChange={handleIsTermChecked} />
Isn't jsx usually surrounded by parentheses?

2021-08-13 17:50 UTC, linkfang commented on src/main/www/src/components/Application/Review/Review.tsx
> +          <Checkbox name="term" color="primary" required checked={isTermChecked} onChange={handleIsTermChecked} />
That will depend on different situations.

When it's a multiple-line one and it's in a return statement or a condition statement ( : ? operator etc.), Prettier will add parentheses to it to make it clearer and easier to read.

Other than that, Prettier won't add one and will even delete the parentheses if there is one. I think because it's already clear enough for people to read.

2021-08-13 17:53 UTC, linkfang commented on src/main/www/src/components/Application/Review/Review.tsx
> +    setIsTermChecked(newIsTermChecked);
Ah, right.
Before I did the latest change, I had to use this value more than 1 time. But later on, I changed the logic based on the feedback and then forgot to change this.

Now it's good.

2021-08-13 18:11 UTC, autumnfound approved these changes

2021-08-19 16:02 UTC, merged