Added validation logic for using steppers
EclipseFdn/react-eclipsefdn-members pull request #309
Opened 2021-08-27 21:22 UTC by linkfang

Fixes [issue304](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/304) and fixes [issue305](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/305)

Added validation logic for using steppers
Improved navigation logic for using steppers

Validation logic for going back:

- If current step is empty and this is the furthest step user has been to, user can go back
- If current step is empty and this is NOT the furthest step user has been to, user can go back, and the values on current step will be reset to a previous valid state. (This will prevent the user skips validation on current step)
- If current step is NOT empty and all the values pass validation, user can go back, and the values will be updated to the database.
- If current step is NOT empty and fails to pass validation, user will see a confirmation modal window. If choose "Yes", user will go back and loses new changes to that step, values will be roll back to previous valid state. If choose "cancel", user will stay on current step.

2021-08-30 14:15 UTC, chrisguindon approved these changes

2021-08-30 15:09 UTC, autumnfound approved these changes

2021-08-30 15:12 UTC, autumnfound requested changes
After these changes, you can no longer go back if you haven't completed the step you are currently on. I think we need a discussion on what we want to do in that case for save events, as it's kind of complicated

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/Utils/formFunctionHelpers.js
> +    setCurrentFormik && setCurrentFormik(formik);
this is a weird line. IF you are munging 2 statements together like this, you should document why

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/Utils/formFunctionHelpers.js
> +  if (isEmpty) formik.setValues(updatedFormValues);
we always add brackets to if statements, as it gets harder to read otherwise

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/Utils/formFunctionHelpers.js
> +  if (!isEmpty && Object.keys(result).length <= 0) formik.submitForm();
we always add brackets to if statements, as it gets harder to read otherwise

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/Utils/formFunctionHelpers.js
> +      if (!isObjectEmpty(element)) return false;
we always add brackets to if statements, as it gets harder to read otherwise

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/Utils/formFunctionHelpers.js
> +    if (key === 'id' || key === 'allWorkingGroups') continue;
we always add brackets to if statements, as it gets harder to read otherwise

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/components/Application/Application.js
> +      const updateFormValuesObj = {
we probably don't need to set this as a const as its being used in the next line

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/components/Application/Application.js
> +    const updateFormValuesObj = {
this can probably inlined rather than setting it like this

2021-09-02 20:28 UTC, autumnfound commented on src/main/www/src/components/Application/WorkingGroups/WorkingGroupsWrapper.js
> +      if (!isObjectEmpty(workingGroups[i])) return false;
we always add brackets to if statements, as it gets harder to read otherwise

2021-09-02 21:10 UTC, linkfang commented on src/main/www/src/Utils/formFunctionHelpers.js
> +    setCurrentFormik && setCurrentFormik(formik);
Ah, OK.
When I tried to add comment about it, I found another way to do it which is easier to read and could keep the parameters in this function cleaner (1 less).

2021-09-03 17:51 UTC, autumnfound reviewed
Just a question...why not set the current step index and max into a context, and ask the context if its on the last page? I'm not sure I get why we need all of the steps to self report an index that may change when it could be managed more fluidly in a central context

2021-09-03 17:54 UTC, autumnfound commented
> Just a question...why not set the current step index and max into a context, and ask the context if its on the last page? I'm not sure I get why we need all of the steps to self report an index that may change when it could be managed more fluidly in a central context

We can look at this as a separate issue if we want to implement this, but I'm wondering why we aren't

2021-09-03 17:58 UTC, linkfang commented
> > Just a question...why not set the current step index and max into a context, and ask the context if its on the last page? I'm not sure I get why we need all of the steps to self report an index that may change when it could be managed more fluidly in a central context
> 
> We can look at this as a separate issue if we want to implement this, but I'm wondering why we aren't

Actually, it's a good idea to make it into a context. The max is in the context now. 
I don't add it in because we did not use it before adding the stepper validation. And now we are using it all over the projects, so making it a context does sound good.

I can make the change in this PR, should be quick and easy.

2021-09-03 18:53 UTC, autumnfound commented
Wow, this is really coming together! Just played around with going back and it looks really good! I think the only thing I want to check on is the working in the modal. WDYT @chrisguindon

2021-09-03 19:07 UTC, chrisguindon commented
@autumnfound I think you meant wording? I agree, I think we can tweak the text a bit:

![Screenshot 2021-09-03 145513](https://user-images.githubusercontent.com/893942/132053718-25d2d1d2-8be4-40c8-b23a-c93e5f168424.png)


How about:

The form submission for this step is incomplete. Are you sure you want to leave without saving?

Keep Editing | Leave 


@shanda-eclipse WDYT?

2021-09-07 19:36 UTC, autumnfound approved these changes

2021-09-07 19:46 UTC, merged