Fixed the scroll up button layout issue
EclipseFdn/react-eclipsefdn-members pull request #312
Opened 2021-08-30 18:14 UTC by linkfang

2021-08-30 18:39 UTC, autumnfound commented
One thing I'm not 100% sure of, on netlify there is no chatbot active so the pointer is oddly placed. Is there ever a case on production where that would not be present?

2021-08-31 12:39 UTC, chrisguindon requested changes
As discussed, we should only move the .scrollup if the chatbox is present on the page: https://legacydocs.hubspot.com/docs/methods/conversations_api/hubspot-conversations-javascript-api

2021-08-31 12:40 UTC, chrisguindon commented
I will ping @shanda-eclipse to see if we can figure a way to include the chatbox on staging/netlify.

2021-09-13 17:12 UTC, autumnfound commented on src/main/www/src/less/App.less
> +  // bottom: 100px;
we should remove these lines if we're on the final version ;)

2021-09-13 17:39 UTC, linkfang commented on src/main/www/src/less/App.less
> +  // bottom: 100px;
Ah, no, this PR is just for testing and preview, the actual changes are in solstice-assets repo (https://github.com/EclipseFdn/solstice-assets/pull/275)

2021-09-20 18:35 UTC, linkfang commented
Closing this PR as the actual patch was merged.

2021-09-20 18:35 UTC, closed without merging