Add Quartz scheduler to clean up stale form entries.
EclipseFdn/react-eclipsefdn-members pull request #313
Opened 2021-08-30 20:28 UTC by autumnfound

2021-08-31 08:19 UTC, mbarbero requested changes

2021-08-31 08:19 UTC, mbarbero commented on src/main/java/org/eclipsefoundation/react/resources/MembershipFormResource.java
> +        mf.setDateUpdated(mf.getDateSubmitted());
My understanding would be to set dateUpdated to current time, and don't change dateSubmitter, ie:

```
mf.setDateSubmitted(mf.getDateSubmitted());
mf.setDateUpdated(System.currentTimeMillis());
```

2021-08-31 08:19 UTC, mbarbero commented on src/main/java/org/eclipsefoundation/react/resources/MembershipFormResource.java
> +        mem.setDateUpdated(mem.getDateCreated());
My understanding would be to set dateCreated to current time, and don't change dateSubmitter, ie:

```
mem.setDateCreated(mf.getDateCreated());
mf.setDateUpdated(System.currentTimeMillis());
```

2021-08-31 12:51 UTC, autumnfound commented on src/main/java/org/eclipsefoundation/react/resources/MembershipFormResource.java
> +        mf.setDateUpdated(mf.getDateSubmitted());
We differentiate 3 dates here. Created, updated, and submitted. The submitted date is set when the form is submitted for membership team approval/next steps. So setting it here is the correct method

2021-08-31 12:53 UTC, autumnfound commented on src/main/java/org/eclipsefoundation/react/resources/MembershipFormResource.java
> +        mem.setDateUpdated(mem.getDateCreated());
I'm setting date updated for simplicity of querying, as otherwise if a user creates a form and never updates any of the fields, then it would be missed from the above query. The framework doesn't support complex queries atm, so I can't add the conditional of if this and that sort of thing.

2021-09-01 07:48 UTC, mbarbero approved these changes

2021-09-03 17:33 UTC, merged