Added flag for showing console logs
EclipseFdn/react-eclipsefdn-members pull request #314
Opened 2021-09-02 20:39 UTC by linkfang

Waiting for [PR309](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/309) to be merged

2021-09-28 19:15 UTC, linkfang commented
Will reopen a new PR against release-1.1 branch

2021-10-04 13:20 UTC, autumnfound requested changes
The change looks like its solid, but you've hidden some error logs which we should avoid doing. The idea with hiding the console logs is to declutter the console in production in case anything breaks to make the issue more clear

2021-10-04 13:20 UTC, autumnfound commented on src/main/www/src/components/Application/CompanyInformation/CompanyInformation.js
> +          !isProd && console.log(err);
We can probably leave this one to display since its an error.

2021-10-04 13:20 UTC, autumnfound commented on src/main/www/src/components/Application/SignIn/SignIn.js
> +        !isProd && console.log(err);
We can probably leave this one to display since its an error.

2021-10-04 13:20 UTC, autumnfound commented on src/main/www/src/components/Application/WorkingGroups/WorkingGroupsWrapper.js
> +      !isProd && console.log(err);
We can probably leave this one to display since its an error.

2021-10-04 13:20 UTC, autumnfound commented on src/main/www/src/components/Application/WorkingGroups/WorkingGroupsWrapper.js
> +      !isProd && console.log(err);
We can probably leave this one to display since its an error.

2021-10-04 13:20 UTC, autumnfound commented on src/main/www/src/components/Portal/NavBar/AppTopBar.tsx
> +          !isProd && console.log(err);
We can probably leave this one to display since its an error.

2021-10-05 14:58 UTC, autumnfound approved these changes

2021-10-06 13:23 UTC, merged