Replaced input components
EclipseFdn/react-eclipsefdn-members pull request #70
Opened 2021-05-11 20:52 UTC by linkfang

Finished:

- Text Field/Input
- Auto Complete (for country input)
- Auto Complete with Creatable feature (for company input)

TBD:

- Auto Complete for working groups
- Auto Complete for participation level

2021-05-12 12:51 UTC, autumnfound commented on src/main/www/src/components/UIComponents/Inputs/Input.js
> +    // ariaLabel,
We should not drop aria label functionality, otherwise, we lose a critical accessibility element

2021-05-12 20:38 UTC, linkfang commented on src/main/www/src/components/UIComponents/Inputs/Input.js
> +    // ariaLabel,
> We should not drop aria label functionality, otherwise, we lose a critical accessibility element

OK, sounds good! 
I will need to add this in later as I don't think it's being used properly/thoroughly in the project.

2021-05-14 12:58 UTC, autumnfound commented
If this is ready for review, when do you plan to remove the unused comments/code?

2021-05-14 13:02 UTC, linkfang commented
> If this is ready for review, when do you plan to remove the unused comments/code?

I am thinking remove them in the integration PR (integrate Formik and Material-UI), as I may refer to the old code to understand how it worked before. Having them in comment could be easier for me.

2021-05-14 13:17 UTC, autumnfound commented
> > If this is ready for review, when do you plan to remove the unused comments/code?
> 
> I am thinking remove them in the integration PR (integrate Formik and Material-UI), as I may refer to the old code to understand how it worked before. Having them in comment could be easier for me.

I'm not a fan of leaving code in when we have VC, but as long as it gets removed then it's alright

2021-05-14 13:21 UTC, autumnfound requested changes
3 issues I saw, 2 are new, one I'm not sure:
- Email validation isn't working on my end (not sure if this one is new)
- Final next button no longer loads a review page
- The "Same as Company Rep" button no longer works
Small potatoes considering how big the change is, looks great otherwise!

2021-05-14 13:30 UTC, linkfang commented
> 3 issues I saw, 2 are new, one I'm not sure:
> 
> * Email validation isn't working on my end (not sure if this one is new)
> * Final next button no longer loads a review page
> * The "Same as Company Rep" button no longer works
>   Small potatoes considering how big the change is, looks great otherwise!

Good catch.
Yeah, all the issues are caused by lacking of integration with Formik.

For validation, we will keep using Formik to do it, and I will do this in another PR (integrate those two)

For the last 2 issues, the value for/in Material-UI are not saved and passed through Formik for now.

So, when select "same as company rep", the value won't be passed into the TextField component. 
And when click Next button to load the review page, same idea, the page/formik is checking the value being saved in Formik and found nothing, even though we type info into those 4 input boxes.

Therefore, all 3 issues will be fixed after I finish integrating Formik with Material-UI in another PR (coming PR).

2021-05-26 21:50 UTC, linkfang commented
> 3 issues I saw, 2 are new, one I'm not sure:
> 
> * Email validation isn't working on my end (not sure if this one is new)
> * Final next button no longer loads a review page
> * The "Same as Company Rep" button no longer works
>   Small potatoes considering how big the change is, looks great otherwise!

Now they are solved.

2021-05-27 19:54 UTC, autumnfound reviewed
Looks good so far, but Zhou mentioned there's a current bug that is being investigated!

2021-05-27 20:02 UTC, chrisguindon commented
I am putting this back as a draft since we do need to resolve the loop issue.

2021-05-28 14:29 UTC, autumnfound commented
Failing due to missing import. Once that's in I think we can merge this!

2021-05-28 15:16 UTC, autumnfound commented
@chrisguindon we good to go with this?

2021-05-28 15:18 UTC, chrisguindon commented
I haven't tested it yet.

2021-05-28 17:30 UTC, merged