Generate kubernetes container definition #11
EclipseFdn/react-eclipsefdn-members pull request #78
Opened 2021-05-27 13:25 UTC by autumnfound

2021-05-27 13:59 UTC, autumnfound commented
This needs a quick update to the build, which will be forthcoming

2021-05-28 07:09 UTC, mbarbero approved these changes

2021-05-31 14:37 UTC, chrisguindon commented on src/main/k8s/production.yml
> +  host: "api.eclipse.org"
I don't think we will want to host this on API staging. I've asked @shanda-eclipse  to confirm the URLs on slack but I am thinking we need the following:

membership.eclipse.org (Enrollment form)
membership.eclipse.org/portal (Membership Portal)
Staging:
membership-staging.eclipse.org (Enrollment form)
membership-staging.eclipse.org/portal (Membership Portal)

2021-05-31 14:38 UTC, chrisguindon requested changes
Let's focus on getting this on staging before production!

2021-05-31 15:53 UTC, shanda-eclipse commented
I can't think of any conflicting uses for membership.eclipse.org, so I think it makes sense to put these on the membership subdomain.

2021-05-31 15:54 UTC, shanda-eclipse commented on src/main/k8s/production.yml
> +  host: "api.eclipse.org"
I can't think of any conflicting uses for membership.eclipse.org, so I think it makes sense to put these on the membership subdomain.

2021-06-01 18:15 UTC, merged